import { Inter } from 'next/font/google'
import './globals.css'
import BotonEnlace from '@/components/BotonEnlace/BotonEnlace'
import Link from 'next/link'
import FondoDinamico from '@/components/FondoDinamico/FondoDinamico'
import TarjetaFiltro from '@/components/TarjetaFiltro/TarjetaFiltro'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container__app'> 
        {children}
        </div>
        <div className='fondoDinamico'>
        <FondoDinamico />
    </div>
        </body>
    </html>
  )
}
