import { Inter } from 'next/font/google'
import './globals.css'
import BotonEnlace from '@/components/BotonEnlace/BotonEnlace'
import Link from 'next/link'
import FondoDinamico from '@/components/FondoDinamico/FondoDinamico'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container__app'>
        <nav className='navBar'>
          <Link href={'/'}>
          <BotonEnlace text={"Home"} />
          </Link>
          <Link href={'/perfil'}>
          <BotonEnlace text={"Perfil"} />
          </Link>
          <Link href={'/misSuenios'}>
          <BotonEnlace text={"Mis sueños"} />
          </Link>
          <Link href={'/favoritos'}>
          <BotonEnlace text={"Mis favoritos"} />
          </Link>
        </nav>
        <main className='main'>
        {children}
        </main>
        </div>
        </body>
    </html>
  )
}
