import { Inter } from 'next/font/google'
import './globals.css'
import BotonEnlace from '@/components/BotonEnlace/BotonEnlace'
import Link from 'next/link'
import FondoDinamico from '@/components/FondoDinamico/FondoDinamico'
import TarjetaFiltro from '@/components/TarjetaFiltro/TarjetaFiltro'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container__app'>
        <nav className='navBar'>
        <h1>Filtrá tu búsqueda</h1>
        <div className='navBar__tarjetas'>
        <TarjetaFiltro text={"Caía"} />
        <TarjetaFiltro text={"Me perseguían"} />
        <TarjetaFiltro text={"Me moría"} />
        <TarjetaFiltro text={"Con un fantasma"} />
        <TarjetaFiltro text={"Ovinis"} />
        <TarjetaFiltro text={"Extraterrestes"} />
        <TarjetaFiltro text={"Volaba"} />
        <TarjetaFiltro text={"Era otra persona"} />
        <TarjetaFiltro text={"Me peleaba"} />
        </div>

        </nav>
        <main className='main'>
        {children}
        </main>
        </div>
        </body>
    </html>
  )
}
